apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleCredential
metadata:
  name: ocp-virt-cred
spec:
  name: ocp-virt-cred
  organization: Default
  connection_secret: awxaccess
  description: "Bearer Credential"
  type: "OpenShift or Kubernetes API Bearer Token"
  kubernetes_api: https://kubernetes.default.svc
  kubernetes_bearer_token_secret: controller-credential
  runner_pull_policy: IfNotPresent